### ISSUE TITLE
Chrome Bookmarks template can't be found

### ISSUE THREAD

**Issue by remcoplasmeyer** [AMKohn/iChrome#18]
The Chrome Bookmarks widget says: 'Template "widgets.chrome_bookmarks" not found!'

**Comment by AMKohn** [comment]
Thanks for catching this, I just found and fixed the issue.  I'm releasing the fix now.

**Comment by AMKohn** [comment]
I __hate__ when this happens.  Both versions should be updating now, thanks again for letting me know.

Avi
