### ISSUE TITLE
New tab version removed from Chrome Web Store

### ISSUE THREAD

**Issue by remcoplasmeyer** [AMKohn/iChrome#19]
If you didn't know already, it seems the new tab version is removed from the store? https://chrome.google.com/webstore/detail/ichrome-new-tab/iccjgbbjckehppnpajnmplcccjcgbdep?hl=en

**Comment by AMKohn** [comment]
It has been, however you can sideload it from this repository without issues.

The bugfix updates I've been trying to release have been blocked by Google.  I tried unpublishing it hoping it would revert to the previous published version and cancel the update that was stuck.  Needless to say it didn't work and the extension is now off the webstore until the updates make it through.

Avi

**Comment by abhimanyusharma003** [comment]
When iChrome New tab will be up again. ?

**Comment by AMKohn** [comment]
Google took the extension down again on Wednesday.  They've done this a number of times now and have failed to point out a single thing wrong with either version.  I'm pretty sure it's because of the code size (~40,000 lines in the end).

I sent them a message, but they don't work weekends so it probably won't be back up until Monday.

**Comment by abhimanyusharma003** [comment]
This is strange they took down extension without proper report, to you as a developer. To be frank this is the best chrome start up extension and i'm using it from over 1 year or so, I will wait for update. Good luck :)

**Comment by AMKohn** [comment]
I was going to let you know that it's back up, but I see you already know!

It was down 6 days this time, this is becoming a more serious problem.  Do you know anyone in the Chrome or Webstore teams at Google that I can reach out to?
