### ISSUE TITLE
[Request] Feedly dropdown selector

### ISSUE THREAD

**Issue by abhimanyusharma003** [AMKohn/iChrome#25]
Hello, 
It's a request to add add dropdown menu for feedly to change the channel (shot articles from) on the fly.

If we disable the editing mode we also loose ability to change the feedly channel. 

I have lot's of subscription on feedly, which can be harder for me to track in grouped list

May be some where in the red portion.

![](http://i.imgur.com/Sx65L0A.png)

Thanks

**Comment by AMKohn** [comment]
I've created an idea for this [on the UserVoice forums](http://ichrome.uservoice.com/forums/205893/suggestions/9379887), since they allow for proper voting.  Please upvote it there.

**Comment by AMKohn** [comment]
I'm curious, why wouldn't you want to just open Feedly?
