### ISSUE TITLE
Hacker News widget

### ISSUE THREAD

**Issue by tracker1** [AMKohn/iChrome#40]
Would like to see a [hacker news](https://news.ycombinator.com/news) widget that's closer to the HN homepage for order, and includes links to the article and comments.

I've been using the rss widget, but feedly tends to lag, and when I click through on the header, I have to hunt for the articles/comments I thought looked interesting.

**Comment by AMKohn** [comment]
I'd like to keep widgets more generic for now and only create ones for specific platforms (such as Feedly and Reddit). In the future I plan to build out a directory of pre-configured widgets for various sites, but not for a while.

Avi

**Comment by thinkingmedia** [comment]
Can't we have a button on the toolbar in Chrome to add the current website's RSS feed as a widget?

**Comment by AMKohn** [comment]
@thinkingmedia That could be cool. The detection code is pretty simple (here's what Google uses: https://gist.github.com/AMKohn/638d675961bf3ea5dcb4), but I'd have to add something to disable the feature (there will be people that won't want it) and handle widget addition. The new widget would have to be highlighted as well.

**Comment by thinkingmedia** [comment]
Yeah, it's more complicated then just adding a button. Maybe you can just store the RSS URL for later use. After clicking the button display a message saying "RSS has been stashed". Next time you add the RSS widget there is a drop down of stashed feeds.
