### ISSUE TITLE
Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'.

### ISSUE THREAD

**Issue by rajdeep26** [AMKohn/iChrome#44]
I get the "Package is invalid. Details: 'Default locale is defined but default data couldn't be loaded.'." error when trying to install from the chrome store.
![selection_749](https://cloud.githubusercontent.com/assets/1943223/15647107/416e104e-267f-11e6-8ec2-ade1c5c5d4de.png)

**Comment by AMKohn** [comment]
I'm not seeing that error on either package from the webstore. What version of Chrome are you running?

BTW, your email address is visible in that image, you might want to remove or update it.

**Comment by rajdeep26** [comment]
Closing this as when i tried to reinstall today, it worked fine.
