### ISSUE TITLE
Clock widget countdown renders itself non-functional if the clock is supposed to ring while the new tab page isn't open

### ISSUE THREAD

**Issue by gkovacs** [AMKohn/iChrome#47]
Steps to reproduce:

Start an alarm with the clock widget (set it at 10 seconds or so)
Navigate to another page. Ensure there are no new tab pages open.
Wait until after the alarm is supposed to go off
When you visit the new tab page again, the clock widget will be gone (replaced with a small block), and it will not be possible to remove it.

Here is a video illustrating the issue using stock unmodified iChrome (current version, 3.0.0.10) with just the clock widget enabled: https://www.youtube.com/watch?v=at8QBJeEu6A

**Comment by gkovacs** [comment]
And here is a more minimal video illustrating the issue using stock unmodified iChrome (current version, 3.0.0.10) with just the clock widget enabled: https://www.youtube.com/watch?v=at8QBJeEu6A

**Comment by AMKohn** [comment]
Thank you for the report. I've tracked down the issue and hope to fix it Sunday.

**Comment by jpgrall** [comment]
I'm having the same issue on version 3.0.38.1 running on chrome 72.0.3626.121. OS is raspbian 9.
