### ISSUE TITLE
System Statistics widget show incorrect memory values

### ISSUE THREAD

**Issue by mcastril** [AMKohn/iChrome#48]
At least on OpenSuse 13.2 memory usage value is always above 90%. CPU stats seem to be ok. Battery value is not so useful on desktop.

**Comment by kserradell** [comment]
Issue confirmed.

3.16.7-21-desktop
Version 54.0.2840.90 (64-bit)

**Comment by AMKohn** [comment]
The data for that widget is provided by Chrome. iChrome just displays the numbers that are returned by the API. If there's an issue on a particular system, please report it to Google via the appropriate Chrome channels.
