### ISSUE TITLE
Can`t log inn

### ISSUE THREAD

**Issue by Harabo** [AMKohn/iChrome#51]
I try to log inn, but the callback dosn`t work

I get to api.ichro.me/oauth/v1/.......

**Comment by AMKohn** [comment]
Hi,

Is this working now? If not, please email a screenshot of the page you're seeing to support@ichro.me

Thanks!

Avi

**Comment by Harabo** [comment]
Hi,

It is not working.

I attach a screenshot:
[cid:96dc2b85-88b2-4d9a-b579-aa6785760a2f]
I use Settings -> Account -> Sign in with google

Have tried different google accounts
________________________________
Fra: Avi Kohn <notifications@github.com>
Sendt: 5. september 2017 01:09
Til: AMKohn/iChrome
Kopi: Harabo; Author
Emne: Re: [AMKohn/iChrome] Can`t log inn (#51)


Hi,

Is this working now? If not, please email a screenshot of the page you're seeing to support@ichro.me<mailto:support@ichro.me>

Thanks!

Avi
